---
- name: Remove Kie Server WAR
  file:
    state: absent
    path: "{{ bpms_kie_server_location }}"

- name: Remove Kie Server Deployment Marker
  file:
    state: absent
    path: "{{ bpms_kie_server_location + '.dodeploy' }}" 

- include: configuration_files.yml

- include: java_opts.yml       
